name: Compile Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: kivy/buildozer-action@v1
        with:
          command: buildozer -v android debug

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: lilit-station-apk
          path: bin/*.apk
